steps:
  # Step 1: Install dependencies in a virtual environment
  - name: 'python:3.9'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        python -m venv /workspace/venv
        source /workspace/venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

  # Step 2: Run tests in the same environment
  - name: 'python:3.9'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/venv/bin/activate
        python -m unittest discover tests

  # Step 3: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/my-project-5-495504/sibadocregistry/myimage/myapp:$BUILD_ID'
      - '.'

  # Step 4: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/my-project-5-495504/sibadocregistry/myimage/myapp:$BUILD_ID'

images:
  - 'us-central1-docker.pkg.dev/my-project-5-495504/sibadocregistry/myimage/myapp:$BUILD_ID'

logsBucket: 'gs://lab2-log-archive-siba'
